/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProductsUpdateIdImport } from './routes/products/update_.$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ProductsAddLazyImport = createFileRoute('/products/add')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProductsAddLazyRoute = ProductsAddLazyImport.update({
  path: '/products/add',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/products/add_.lazy').then((d) => d.Route))

const ProductsUpdateIdRoute = ProductsUpdateIdImport.update({
  path: '/products/update/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/products/add': {
      id: '/products/add'
      path: '/products/add'
      fullPath: '/products/add'
      preLoaderRoute: typeof ProductsAddLazyImport
      parentRoute: typeof rootRoute
    }
    '/products/update/$id': {
      id: '/products/update/$id'
      path: '/products/update/$id'
      fullPath: '/products/update/$id'
      preLoaderRoute: typeof ProductsUpdateIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ProductsAddLazyRoute,
  ProductsUpdateIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/products/add",
        "/products/update/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/products/add": {
      "filePath": "products/add_.lazy.tsx"
    },
    "/products/update/$id": {
      "filePath": "products/update_.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
